apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: quickstart
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: quickstart-es-http.fluent.svc
    port: 9200
    index: "cluster"
    traceOutput: True
    generateID: true
    traceError: true
    httpUser:
      valueFrom:
        secretKeyRef:
          key: user
          name: es-user-pw
    httpPassword:
      valueFrom:
        secretKeyRef:
          key: elastic
          name: es-user-pw
    suppressTypeName: "On"