apiVersion: v1
kind: Kibana
metadata:
  name: elasticsearch-master
spec:
  version: 8.5.1
  count: 2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: elasticsearch-master